app:
  last_open_dir: .
path:
  osu_path: C:/MyOtherFiles/osu!/Songs/1841885 cYsmix - triangles/cYsmix - triangles
    (yf_bmp) [Easy].osu
  output_path: C:/MyOtherFiles/osu!/Songs/1841885 cYsmix - triangles/cYsmix - triangles
    (yf_bmp) [Chaoz's Expert].mp4
renderer:
  crf: 20
  enable_audio: true
  encoder_preset: fast
  fps: 60
  height: 720
  sample_method: linear
  use_gpu: true
  width: 1280
