app:
  last_open_dir: .
path:
  osu_path: ./example.osu
  output_path: ./output.mp4
renderer:
  crf: 20
  enable_audio: true
  encoder_preset: fast
  ffmpeg_path: ""   # empty = auto-detect; set to custom ffmpeg.exe path
  fps: 60
  height: 720
  sample_method: linear
  use_gpu: true
  width: 1280
